all:
  vars:
      ansible_user: manager
      ansible_become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_python_interpreter: /bin/ash
  hosts:

    router1:
        ansible_host: 192.168.1.2
        interfaces:
            lo: 1.0.0.1/32
            eth1: 10.0.0.1/30
            eth2: 10.0.0.5/30
            eth3: 10.0.0.9/30
            eth4: 10.0.0.13/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4

    router2:
        ansible_host: 192.168.1.3
        interfaces:
            lo: 1.0.0.2/32
            eth1: 10.0.1.1/30
            eth2: 10.0.1.5/30
            eth3: 10.0.1.9/30
            eth4: 10.0.1.13/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4

    router3:
        ansible_host: 192.168.1.4
        interfaces:
            lo: 2.0.0.1/32
            eth1: 10.0.0.2/30
            eth2: 10.0.1.2/30
            eth3: 172.16.1.1/24
        neighbors:
            - 1.0.0.1
            - 1.0.0.2
        server_neighbors:
            - 172.16.1.2

    router4:
        ansible_host: 192.168.1.5
        interfaces:
            lo: 2.0.0.2/32
            eth1: 10.0.0.6/30
            eth2: 10.0.1.6/30
            eth3: 172.16.2.1/24
        neighbors:
            - 1.0.0.1
            - 1.0.0.2
        server_neighbors:
            - 172.16.2.2

    router5:
        ansible_host: 192.168.1.6
        interfaces:
            lo: 2.0.0.3/32
            eth1: 10.0.0.10/30
            eth2: 10.0.1.10/30
            eth3: 172.16.3.1/24
        neighbors:
            - 1.0.0.1
            - 1.0.0.2
        server_neighbors:
            - 172.16.3.2

    router6:
        ansible_host: 192.168.1.7
        interfaces:
            lo: 2.0.0.4/32
            eth1: 10.0.0.14/30
            eth2: 10.0.1.14/30
            eth3: 172.16.4.1/24
        neighbors:
            - 1.0.0.1
            - 1.0.0.2
        server_neighbors:
            - 172.16.4.2

    server1:
        ansible_host: 192.168.1.8
        server_net_ip: 172.16.1.2
        gateway: 172.16.1.1
        interfaces:
            eth1: 172.16.1.2/24
        ips_vm: 
            - 8.8.8.1
            - 8.8.8.2
        leafs:
            - 172.16.1.1  

    server2:
        ansible_host: 192.168.1.9
        server_net_ip: 172.16.2.2
        gateway: 172.16.2.1
        interfaces:
            eth1: 172.16.2.2/24
        ips_vm:
            - 8.8.8.3
            - 8.8.8.4
        leafs:
            - 172.16.2.1

    server3:
        ansible_host: 192.168.1.10
        server_net_ip: 172.16.3.2
        gateway: 172.16.3.1
        interfaces: 
            eth1: 172.16.3.2/24
        ips_vm:
            - 8.8.8.5
            - 8.8.8.6
        leafs:
            - 172.16.3.1

    server4:
        ansible_host: 192.168.1.11
        server_net_ip: 172.16.4.2
        gateway: 172.16.4.1
        interfaces:
            eth1: 172.16.4.2/24
        ips_vm:
            - 8.8.8.7
            - 8.8.8.8
        leafs:
            - 172.16.4.1

spines:
    hosts:
        router1:
        router2:

leafs:
    hosts:
        router3:
        router4:
        router5:
        router6:

servers:
    hosts:
        server1:
        server2:
        server3:
        server4:
