all:
  vars:
      ansible_user: manager
      ansible_become: true
      ansible_become_method: su
      ansible_become_user: root
      ansible_python_interpreter: /bin/ash
  hosts:
    router1:
        ansible_host: 192.168.1.2
        interfaces:
            lo: 1.0.0.1/32
            eth2: 10.0.0.1/30
            eth3: 10.0.0.5/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
    router2:
        ansible_host: 192.168.1.3
        interfaces:
            lo: 1.0.0.2/32
            eth2: 10.0.1.1/30
            eth3: 10.0.1.5/30
        neighbors:
            - 2.0.0.1
            - 2.0.0.2
            - 2.0.0.3
            - 2.0.0.4
  
spines:
    hosts:
        router1:
        router2:
      
      
      
