- name: Configurar nodos leaf
  hosts: leafs
  gather_facts: no
  become: yes
  become_method: su
  become_user: root

  tasks:
    - name: Crear bridge br0
      raw: |
        ip link add br0 type bridge
        ip link set br0 up 
        ip link set eth3 master br0
        ip link set eth3 up

    - name: Configurar interfaces del nodo
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "interface {{ item.key }}" \
        vtysh -c "ip address {{ item.value }}" \
        vtysh -c "ip ospf area 0" \
        vtysh -c "exit"
      loop: "{{ interfaces | dict2items }}"
      when: interfaces is defined

    - name: Activar OSPF
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router ospf" \
        vtysh -c "exit"

    - name: Activar BGP y configurar peer-group
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor dc peer-group" \
        vtysh -c "neighbor dc remote-as 65100" \
        vtysh -c "neighbor dc update-source lo" \
        vtysh -c "address-family l2vpn evpn" \
        vtysh -c "exit" \
        vtysh -c "exit"
    
    - name: Configurar leaf peer-group
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor leafs peer-group" \
        vtysh -c "neighbor leafs remote-as 65100" \
        vtysh -c "neighbor leafs update-source lo" \
        vtysh -c "address-family l2vpn evpn" \
        vtysh -c "neighbor leafs route-reflector-client" \
        vtysh -c "exit" \
        vtysh -c "exit"

    - name: Configurar vecinos BGP (los spine)
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor {{ item }} peer-group dc" \
        vtysh -c "exit" \
        vtysh -c "exit"
      with_items: "{{ neighbors }}"
      when: neighbors is defined

    - name: Configurar vecinos BGP (los leafs)
      raw: |
        vtysh -c "configure terminal" \
        vtysh -c "router bgp 65100" \
        vtysh -c "neighbor {{ item }} peer-group leafs" \
        vtysh -c "exit" \
        vtysh -c "exit"
      with_items: "{{ server_neighbors }}"
      when: server_neighbors is defined

    - name: Guardar configuración
      raw: |
        vtysh -c "copy running-config startup-config"